name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # readme formatting
    - name: Test README.rst
      run: |
        sudo apt-get update -y && sudo apt install -y docutils-common # dependencies
        python3 setup.py --long-description | rst2html --strict --no-raw > /dev/null
        pip install -e .
        python -m doctest README.rst
    - name: Fairyfishnet Tests
      run: |
        python3 test.py